exclude:
  - README.md
  - CONTRIBUTING.md
highlighter: pygments
permalink: none
defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
    values:
      layout: "default"
